version: '3.7'

services:
  sngpublicapi:
    image: ${REGISTRY:-ows}/sngpublicapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: SNGPublicAPI/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
     - OWSAPIPathConfig__InternalPublicApiURL=${InternalPublicApiURL}
     - OWSAPIPathConfig__InternalInstanceManagementApiURL=${InternalInstanceManagementApiURL}
     - OWSAPIPathConfig__InternalCharacterPersistenceApiURL=${InternalCharacterPersistenceApiURL}
    ports:
      - "44340:80"
      - "44341:443"
    depends_on:
      - database
      - messaging